Repository ToucanToco/fastexcel, pull requests merged in 2022-10, with the labels that each got.

#14 chore: v0.1.1
  pyproject.toml
Labels: chore, :hand: need review :hand:

#20 feat: Introduce `ExcelSheet` object in the API
  .flake8
  pyproject.toml
  python/fastexcel/__init__.py
  python/fastexcel/fastexcel.pyi
  src/core.rs
  src/lib.rs
  src/types/excelreader.rs
  src/types/excelsheet.rs
  src/types/mod.rs
  src/utils/arrow.rs
  src/utils/mod.rs
  test.py
Labels: enhancement, :hand: need review :hand:, :snake: python :snake:, :crab: rust :crab:

#21 docs: Updated dev documentation and added a Makefile
  .github/workflows/CI.yml
  Makefile
  README.md
  prod_install.sh
Labels: enhancement, :hand: need review :hand:, github_actions

#24 fix(python): Forward __repr__ methods to wrapper classes
  python/fastexcel/__init__.py
Labels: bug, :hand: need review :hand:, :snake: python :snake:

#25 feat(rust/utils/arrow): Provide a default name for unnamed columns
  src/utils/arrow.rs
Labels: enhancement, :hand: need review :hand:, :crab: rust :crab:

#26 fix(rust/ExcelSheet): Subtract 1 from the height to avoid counting the header
  src/types/excelsheet.rs
Labels: bug, :hand: need review :hand:, :crab: rust :crab:

#27 feat(rust): Add support for DateTimes
  Cargo.lock
  Cargo.toml
  src/types/excelsheet.rs
  src/utils/arrow.rs
Labels: enhancement, :hand: need review :hand:, :crab: rust :crab:

#28 ci: Introduce tests
  .github/workflows/CI.yml
  .gitignore
  Makefile
  README.md
  pyproject.toml
  python/tests/fixtures/fixture-multi-sheet.xlsx
  python/tests/fixtures/fixture-single-sheet-with-types.xlsx
  python/tests/fixtures/fixture-single-sheet.xlsx
  python/tests/test_fastexcel.py
  test-requirements.txt
Labels: chore, github_actions, :snake: python :snake:

#30 Header support
  .gitignore
  python/fastexcel/__init__.py
  python/fastexcel/_fastexcel.pyi
  python/tests/fixtures/fixture-changing-header-location.xlsx
  python/tests/test_fastexcel.py
  src/types/excelreader.rs
  src/types/excelsheet.rs
  src/utils/arrow.rs
Labels: :hammer: WIP :wrench:

#38 chore(deps): bump calamine 0.18.0 -> 0.19.1
  Cargo.lock
  Cargo.toml
  src/types/excelreader.rs
Labels: chore, :hand: need review :hand:, dependencies, :crab: rust :crab:

#34 refactor(types/ExcelSheet): Stop bearing a reference to an arrow schema
  python/tests/test_fastexcel.py
  src/types/excelreader.rs
  src/types/excelsheet.rs
  src/utils/arrow.rs
Labels: enhancement, :hand: need review :hand:, :crab: rust :crab:

#39 feat(CI/release): Auto-generate release notes
  .github/workflows/release.yml
Labels: chore, :hand: need review :hand:

#40 chore: v0.2.0
  Cargo.lock
  Cargo.toml
Labels: chore, :hand: need review :hand:

#43 chore: v0.2.1
  Cargo.lock
  Cargo.toml
Labels: chore, :hand: need review :hand:

#44 Pagination
  python/fastexcel/__init__.py
  python/fastexcel/_fastexcel.pyi
  python/tests/test_fastexcel.py
  src/types/excelreader.rs
  src/types/excelsheet.rs
  src/utils/arrow.rs
Labels: enhancement, :hand: need review :hand:, :snake: python :snake:, :crab: rust :crab:

#46 chore: v0.3.0
  Cargo.lock
  Cargo.toml
Labels: chore, :hand: need review :hand:
