Repository ToucanToco/fastexcel, pull requests merged in 2023-01, with the labels that each got.

#64 docs: Added a way to build HTML docs with pdoc
  .gitignore
  Makefile
  README.md
  doc-requirements.txt
  python/fastexcel/__init__.py
Labels: documentation, chore, :hand: need review :hand:, :snake: python :snake:

#65 feat(docs): Added an automatic doc build job
  .github/workflows/docs.yml
Labels: documentation, chore, :hand: need review :hand:

#66 fix(ci/docs): Install missing dependencies
  .github/workflows/docs.yml
Labels: bug, chore, github_actions

#67 fix(ci/docs): Create a venv for maturin
  .github/workflows/docs.yml
Labels: bug, chore, :hand: need review :hand:

#73 fix: change legacy [args] macros
  src/types/excelreader.rs
Labels: chore, :hand: need review :hand:, :crab: rust :crab:
