Repository ToucanToco/fastexcel, pull requests merged in 2024-07, with the labels that each got.

#241 chore(deps): bump pyo3 0.20.3 -> 0.21.2
  Cargo.lock
  Cargo.toml
  pyproject.toml
  src/lib.rs
  src/types/dtype.rs
  src/types/idx_or_name.rs
  src/types/python/excelreader.rs
  src/types/python/excelsheet/mod.rs
Labels: enhancement, chore, dependencies, :crab: rust :crab:

#244 fix: treat #REF! cells as nulls
  python/tests/fixtures/sheet-with-na.xlsx
  python/tests/test_fastexcel.py
  src/types/dtype.rs
Labels: bug, :hand: need review :hand:, :crab: rust :crab:

#245 refactor(dtype): automatically cast mixed string and date columns to strings
  python/tests/fixtures/fixture-multi-dtypes-columns.xlsx
  python/tests/test_dtypes.py
  src/types/dtype.rs
Labels: :hand: need review :hand:, :crab: rust :crab:

#248 feat: add an option to disable automatic type coercion
  python/fastexcel/__init__.py
  python/fastexcel/_fastexcel.pyi
  python/tests/test_dtypes.py
  src/types/dtype.rs
  src/types/python/excelreader.rs
  src/types/python/excelsheet/column_info.rs
  src/types/python/excelsheet/mod.rs
  src/types/python/excelsheet/sheet_data.rs
  test.py
Labels: enhancement, :snake: python :snake:, :crab: rust :crab:

#251 feat: cast bools to strings if mixed types
  python/tests/fixtures/fixture-multi-dtypes-columns.xlsx
  python/tests/test_dtypes.py
  src/types/dtype.rs
  src/types/python/excelsheet/sheet_data.rs
Labels: enhancement, :crab: rust :crab:

#253 chore: v0.11.0
  Cargo.lock
  Cargo.toml
Labels: chore, :hand: need review :hand:

#260 fix: take use_columns into account when loading a sheet eagerly
  python/tests/test_column_selection.py
  src/types/python/excelreader.rs
Labels: bug, :crab: rust :crab:

#261 chore: v0.11.1
  Cargo.lock
  Cargo.toml
Labels: chore

#262 fix: respect provided column ordering in use_columns when loading a sheet eagerly
  python/tests/conftest.py
  python/tests/test_column_selection.py
  python/tests/test_fastexcel.py
  src/types/python/excelreader.rs
  src/types/python/excelsheet/column_info.rs
  src/types/python/excelsheet/mod.rs
Labels: bug, :hand: need review :hand:, :crab: rust :crab:

#264 chore: v0.11.2
  Cargo.lock
  Cargo.toml
Labels: chore

#263 feat(ci): switch to uv
  Makefile
  build-requirements.txt
  prod_install.sh
  pyproject.toml
  test-requirements.txt
Labels: enhancement, :hand: need review :hand:, github_actions

#266 fix(ci): fix interpreter used by maturin
  .github/workflows/CI.yml
  .github/workflows/release.yml
Labels: bug, github_actions

#267 chore: v0.11.3
  Cargo.lock
  Cargo.toml
Labels: chore

#270 fix(ci): bump macos runners to 14 and explcitly specify targets on macos
  .github/workflows/CI.yml
  .github/workflows/release.yml
Labels: bug

#271 chore: v0.11.4
  Cargo.lock
  Cargo.toml
Labels: chore
