Repository ToucanToco/fastexcel, pull requests merged in 2024-10, with the labels that each got.

#298 build(deps): bump arrow to 53.1.0 and pyo3 to 0.22.3
  Cargo.lock
  Cargo.toml
  python/fastexcel/__init__.py
  python/fastexcel/_fastexcel.pyi
  src/lib.rs
  src/types/dtype.rs
  src/types/python/excelreader.rs
  src/types/python/excelsheet/mod.rs
Labels: dependencies

#300 build(deps): clean Cargo.toml and update lock file
  .gitignore
  Cargo.lock
  Cargo.toml
Labels: :hand: need review :hand:, dependencies

#297 feat!: `header_row` is now the exact index of the row when loading a sheet
  python/fastexcel/__init__.py
  python/fastexcel/_fastexcel.pyi
  python/tests/fixtures/no-header.xlsx
  python/tests/test_durations.py
  python/tests/test_fastexcel.py
  src/types/python/excelreader.rs
Labels: :hand: need review :hand:, :snake: python :snake:, :crab: rust :crab:

#299 feat: add support for one dtype for all columns
  python/fastexcel/__init__.py
  python/fastexcel/_fastexcel.pyi
  python/tests/test_dtypes.py
  src/types/dtype.rs
  src/types/python/excelreader.rs
  src/types/python/excelsheet/column_info.rs
  src/types/python/excelsheet/mod.rs
  src/types/python/table.rs
Labels: enhancement, :crab: rust :crab:

#304 feat: forbid schema_sample_rows=0
  python/fastexcel/__init__.py
  python/tests/test_errors.py
  src/types/python/excelreader.rs
Labels: enhancement, :hand: need review :hand:, :crab: rust :crab:

#307 feat: fallback to string if dtype cannot be infered
  Cargo.lock
  Cargo.toml
  pyproject.toml
  python/tests/fixtures/infer-dtypes-fallback.xlsx
  python/tests/test_dtypes.py
  src/lib.rs
  src/types/dtype.rs
  test-requirements.txt
Labels: enhancement, :crab: rust :crab:

#254 ci: add Python 3.13
  .github/workflows/CI.yml
  pyproject.toml
Labels: github_actions
