Repository ToucanToco/fastexcel, pull requests merged in 2025-01, with the labels that each got.

#321 consider `#NUM!` error type as `None`
  python/tests/fixtures/fixture-invalid-cell-value-num.xlsx
  python/tests/test_fastexcel.py
  src/types/dtype.rs
Labels: bug, :hand: need review :hand:, :crab: rust :crab:

#322 chore: v0.12.1
  Cargo.lock
  Cargo.toml
Labels: chore, :hand: need review :hand:

#323 chore: drop support for Python 3.8
  .github/workflows/CI.yml
  .github/workflows/release.yml
  Cargo.toml
  README.md
  pyproject.toml
Labels: chore, :hand: need review :hand:, :snake: python :snake:

#325 feat(deps): upgrade pyo3
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/types/dtype.rs
  src/types/idx_or_name.rs
  src/types/python/excelreader.rs
  src/types/python/excelsheet/mod.rs
  src/types/python/table.rs
Labels: enhancement, :hand: need review :hand:, dependencies, :crab: rust :crab:
